### ISSUE TITLE
firewall_rule does not accept array as argument to port if argument is a node attribute

### ISSUE THREAD

**Issue by Poohblah** [chef-cookbooks/firewall#120]
I'm declaring `firewall_rule` resources like so, where `node['cub_monitoring']['tcp_ports']` and `node['cub_monitoring']['udp_ports']` are Arrays:
```
node['cub_monitoring']['monitoring_hosts'].each do |h|
  firewall_rule "allow #{h} on tcp ports" do
    port node['cub_monitoring']['tcp_ports']
    source h
  end
  firewall_rule "allow #{h} on udp ports" do
    port node['cub_monitoring']['udp_ports']
    source h
  end
end
```
This results in the following exception at converge time:
```
================================================================================
Error executing action `restart` on resource 'firewall[default]'
================================================================================

Chef::Exceptions::ImmutableAttributeModification
------------------------------------------------
Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"' 

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/firewall/libraries/helpers.rb:13:in `port_to_s'
/tmp/kitchen/cache/cookbooks/firewall/libraries/helpers_iptables.rb:37:in `build_firewall_rule'/tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_iptables.rb:84:in `block (3 levels) in <class:FirewallIptables>'
/tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_iptables.rb:82:in `each'
/tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_iptables.rb:82:in `block (2 levels) in <class:FirewallIptables>'
/tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_iptables.rb:71:in `each'
/tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_iptables.rb:71:in `block in <class:FirewallIptables>'

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/firewall/recipes/default.rb

 22: firewall 'default' do
 23:   ipv6_enabled node['firewall']['ipv6_enabled']
 24:   action :install
 25: end
 26: 

Compiled Resource:
------------------
# Declared in /tmp/kitchen/cache/cookbooks/firewall/recipes/default.rb:22:in `from_file'

firewall("default") do
  action [:install] 
  updated true
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :firewall
  cookbook_name "firewall"
  recipe_name "default"
  ipv6_enabled true
  enabled true
  rules {"iptables"=>{"*filter"=>1, ":INPUT DROP"=>2, ":FORWARD DROP"=>3, ":OUTPUT ACCEPT"=>4, "COMMIT_FILTER"=>100, "-A INPUT -p tcp -m tcp -m multiport --dports 22 -m comment --comment \"allow world to ssh\" -j ACCEPT"=>50, "-A INPUT -m state --state RELATED,ESTABLISHED -m comment --comment \"established\" -j ACCEPT"=>50}, "ip6tables"=>{"*filter"=>1, ":INPUT DROP"=>2, ":FORWARD DROP"=>3, ":OUTPUT ACCEPT"=>4, "COMMIT_FILTER"=>100, "-A INPUT -m state --state RELATED,ESTABLISHED -m comment --comment \"established\" -j ACCEPT"=>50, "-A INPUT -p ipv6-icmp -m comment --comment \"ipv6_icmp\" -j ACCEPT"=>50}}
end
```
It appears that this error can be reproduced by passing an array stored as a node attribute to the `port` attribute of the `firewall_rule` resource.  I believe the exception is due to the following code in the `port_to_s` method defined in `libraries/helpers.rb`:
```
      elsif p && p.is_a?(Array)
        p.map! { |o| port_to_s(o) }
        p.sort.join(',')
```
This code is attempting to perform an in-place modification of the port attribute.  This fails if the port attribute is a node attribute.

However, if I declare my firewall rules like this (note the addition of the `.dup` method to copy the array to a new object)...
```
node['cub_monitoring']['monitoring_hosts'].each do |h|
  firewall_rule "allow #{h} on tcp ports" do
    port node['cub_monitoring']['tcp_ports'].dup
    source h
  end
  firewall_rule "allow #{h} on udp ports" do
    port node['cub_monitoring']['udp_ports'].dup
    source h
  end
end
```
...then no exception is thrown.

**Comment by martinb3** [comment]
Ah -- thank you for the bug report. We should definitely not touch the value passed to us :)

**Comment by martinb3** [comment]
Should be fixed and I'll release a new patch version. Thanks again!
