### ISSUE TITLE
NAT rules do not work when using iptables because of ipv6

### ISSUE THREAD

**Issue by alexanderBendo** [chef-cookbooks/firewall#138]
### Cookbook version
2.5.0

### Chef-client version
12.9.38

### Platform Details
Ubuntu 12.04.5 LTS precise
iptables 1.4.12-1ubuntu5

### Scenario:
As stated in the documentation, I have the following configuration in order to redirect a port:

```
firewall_rule 'logstash snmp' do
  raw '-A PREROUTING -p udp --dport 1062 -j REDIRECT --to-port 162'
  position 150
end
```
This requires to use iptables, for it seems you can't use ufw to do the job. So I set `ubuntu_iptables` to `true`.

The problem is that this command works with iptables but not with ip**6**tables

```
# ip6tables -t nat -A PREROUTING -p tcp --dport 80 -m cpu --cpu 1 -j REDIRECT --to-port 8081
ip6tables v1.4.12: unknown option "--to-port"
Try `ip6tables -h' or 'ip6tables --help' for more information.
```

This causes the chef run to fail.

### Steps to Reproduce:
* Use iptables instead of ufw

`default['firewall']['ubuntu_iptables'] = true`

* Add this attribute

```
default['firewall']['iptables']['defaults'][:ruleset] = {
  '*filter' => 1,
  ':INPUT DROP' => 2,
  ':FORWARD DROP' => 3,
  ':OUTPUT ACCEPT' => 4,
  'COMMIT_FILTER' => 100,
  '*nat' => 101,
  ':PREROUTING ACCEPT' => 102,
  ':POSTROUTING ACCEPT' => 103,
  ':OUTPUT ACCEPT' => 104,
  'COMMIT_NAT' => 200
}
```

* Add this rule

```
firewall_rule 'logstash snmp' do
  raw '-A PREROUTING -p udp --dport 1062 -j REDIRECT --to-port 162'
  position 150
end
```
* Converge the node

### Expected Result:
Chef client run OK

### Actual Result:
```
           ================================================================================
           Error executing action `start` on resource 'service[iptables-persistent]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /etc/init.d/iptables-persistent start ----
           STDOUT: * Loading iptables rules...
            *  IPv4...
            *  IPv6...
       ...fail!
           STDERR: 
           ---- End output of /etc/init.d/iptables-persistent start ----
           Ran /etc/init.d/iptables-persistent start returned 1
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_iptables_ubuntu.rb
           
            53:         service 'iptables-persistent' do
            54:           action [:enable, :start]
            55:         end
            56:       end
            56:       end                                                                                                                                      [18/3612]
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_iptables_ubuntu.rb:53:in `block (2 levels) in <class:FirewallIptablesUbuntu>'
           
           service("iptables-persistent") do
             action [:enable, :start]
             supports {:restart=>nil, :reload=>nil, :status=>nil}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "iptables-persistent"
             enabled true
             pattern "iptables-persistent"
             declared_type :service
             cookbook_name "blackbox"
           end
           
           Platform:
           ---------
           x86_64-linux
           
       
       Running handlers:
       [2016-05-20T13:31:44+02:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-05-20T13:31:44+02:00] ERROR: Exception handlers complete
       Chef Client failed. 9 resources updated in 52 seconds
       [2016-05-20T13:31:44+02:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-05-20T13:31:44+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-05-20T13:31:44+02:00] ERROR: service[iptables-persistent] (/tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_iptables_ubuntu.rb line 53) ha
d an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of /etc/init.d/iptables-persistent start ----
       STDOUT: * Loading iptables rules...
        *  IPv4...
        *  IPv6...
          ...fail!
       STDERR: 
       ---- End output of /etc/init.d/iptables-persistent start ----
       Ran /etc/init.d/iptables-persistent start returned 1
       [2016-05-20T13:31:45+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by alexanderBendo** [comment]
It works in Ubuntu 14.04 with iptables 1.4.21-1ubuntu1 so it seems to be a bug in iptables. Unfortunately the latest version available in Ubuntu 12.04 is 1.4.12. You may want to add this to the README.

**Comment by voleoo** [comment]
same issue

**Comment by martinb3** [comment]
Hi there -- could you all try the `ubuntu_iptables_ipv6` branch of the cookbook, and then disable `node['firewall']['ipv6_enabled'] = false`? Thanks!

**Comment by alexanderBendo** [comment]
@martinb3 Tested! The change works for me. Thanks!

**Comment by martinb3** [comment]
Great! I've merged the changes into master, and will do a release immediately. Thanks all!
