### ISSUE TITLE
Build broken on chefspec with chef-sugar 

### ISSUE THREAD

**Issue by martinb3** [chef-cookbooks/firewall#89]
Looks like chef-sugar got removed from the Gemfile in https://github.com/chef-cookbooks/firewall/commit/6c87861c08947181c577fc8b2ac18bcad18d8bf5.

```
LoadError
---------
cannot load such file -- chef/sugar
Cookbook Trace:
---------------
  /tmp/d20150909-2457-1ro2ple/cookbooks/chef-sugar/recipes/default.rb:34:in `require'
  /tmp/d20150909-2457-1ro2ple/cookbooks/chef-sugar/recipes/default.rb:34:in `from_file'
  /tmp/d20150909-2457-1ro2ple/cookbooks/firewall/recipes/default.rb:20:in `from_file'
```

/cc @tas50

**Comment by martinb3** [comment]
Looks like I've also lost push access to fix it :/

**Comment by martinb3** [comment]
Fixed in https://github.com/chef-cookbooks/firewall/commit/8065c8a5d33e5c2021bc72cf23af92f4904ebafe. Thanks @tas50!
